import {
  AUTHENTICATION_COOKIE_NAME,
  AUTOHOUSE_ID_COOKIE_NAME,
} from "@/lib/definitions";
import Footer from "@/ui/footer";
import Header from "@/ui/header";
import Wrapper from "@/ui/wrapper";
import type { Metadata } from "next";
import { Chakra_Petch } from "next/font/google";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import "../globals.css";

const chakraPetch = Chakra_Petch({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get(AUTHENTICATION_COOKIE_NAME)?.value;
  const autoHouseId = cookieStore.get(AUTOHOUSE_ID_COOKIE_NAME)?.value;

  if (!token || !autoHouseId) redirect("/unauthorized");

  return (
    <html lang="en">
      <body className={`${chakraPetch.className} bg-bg antialiased`}>
        <Wrapper>
          <Header />
          {children}
          <Footer />
        </Wrapper>
      </body>
    </html>
  );
}
